version: 2
jobs:
  build:
    steps:
      - checkout
      - run: mkdir build
      - run: cd build
      - run: cmake ..
      - run: cmake --build .
workflows:
  version: 2
  build:
    jobs:
      - build
