version: 2
jobs:
  build:
    docker:
      - image: enumack/buildcontainers:gcc-8.1
    steps:
      - checkout
      - run: ls
      - run: mkdir build
      - run: cd build
      - run: cmake ..
      - run: cmake --build .
workflows:
  version: 2
  build:
    jobs:
      - build
