version: 2
jobs:
  gcc:
    working_directory: /ws
    docker:
      - image: enumack/buildcontainers:gcc-8.1
    steps:
      - checkout
      - run: mkdir build && cd build && cmake .. && cmake --build .
  clang:
    working_directory: /ws
    docker:
      - image: enumack/buildcontainers:clang-4.0.1
    steps:
      - checkout
      - run: mkdir build && cd build && cmake .. && cmake --build .
workflows:
  version: 2
  build:
    jobs:
      - build
